### ISSUE TITLE
Need help to install Dateentry module in perl/tk

### ISSUE THREAD

**Issue by amrita1983** [eserte/tk-dateentry#1]
Hi,

I was trying a program to use DateEntry and this error came 
Can't locate Tk/DateEntry.pm in @INC (you may need to install the Tk::DateEntry module)
I don't know how to fix it, tried to copy this makefile and use it but that is also not working. Please help.

**Comment by eserte** [comment]
Sorry, didn't see this issue earlier.

Easiest is to use cpan or cpanm to install Perl modules:
```cpan Tk::DateEntry``` (one-time configuration needed here)
or
```cpanm Tk::DateEntry``` (maybe cpanm has to be installed first)

Alternatively you can install modules manually, as described in https://github.com/eserte/tk-dateentry/blob/master/README#L6
